# use_logo如果为true, 需要在logo_image设置路径
use_logo: false
logo_image:  # 使用路径, 填写文件名即可(比如, logo_image: logo.png 指向 source/imgs/logo.png)
navbar_text: # 如果没有Logo, 则设置为false, 并且设置navbar_text(否则默认为站点标题, 最好进行设置)

# 必填, 设定小型设备展示背景图, 指向source/imgs, 比如xs_bg_image: bg.png -> source/imgs/bg.png
xs_bg_image: xsbg.jpg

# 必填, 个人头像, 如果是路径, 则指向source/imgs
# 也可以填http:// OR https:// url地址
author_image: /head.png

# 程序员模式, 适合于用该程序的爱好写技术文章的人员, 默认不开启
# 选择开启后将会改变article-excerpt, article-content等的显示
programmer_mode: false

# 导航菜单
menu:
  # index
  - title: 首页
    # 参照font-awesome官网的icon, 取后面一段(比如用fa-star这个图标, 那么这里的icon就填star)
    icon: home
    url: /
  # archives
  - title: 文章
    icon: archive
    url: archives
  # categories
  - title: 分类
    icon: list
    url: categories
    dropdown: 3 #dropdown为下拉菜单出现的项目最大数目(只限于tags和categorys)
    # 如果不想显示下拉菜单, 则不要填写, 即dropdown:
    # 具体效果可以看https://myau.moe
  # tags
  - title: 标签
    icon: tags
    url: tags
    dropdown: 3
  # about, 这个实际上是自定义page, 后面的自定义page参照about样式
  - title: 关于我
    icon: user
    url: /2020/06/02/我的回忆/

# 每篇文章的preview默认图片
# 必填项(除非你每篇文章的front-matter都设置了preview属性)
# 填写: 可以放多张图, 将随机抽取作为默认的preview图片
# 如果使用文件名则对应目录: source/imgs/preview, 比如 preview1.jpg -> source/imgs/preview/preview1.jpg
# 如果用url则填写完整的url地址即可
default_preview:
  - t01d54a78939622a708.jpg
  - t01b5b4a7529cad373b.jpg
  - t01260c377a60ef55b8.jpg
  - t01b32959885c781013.jpg
  - t01c37e049c18d00e4c.jpg
  - t01e75d2d4734b2c35e.jpg
  - t013698845e810692d8.jpg
  - t012ec64f1e1eb1d23f.jpg
  - t012db749fb526b27cf.jpg
  - t01a2e705e6e2514c91.jpg
  - t0106a9c2522bdd29f7.jpg
  - t0192efea6a01252f4e.jpg
  - t01794a9e0bc4321c3c.jpg
  - t01d2ed30550310750e.jpg
  - t01a98dd6f6ea17e633.jpg
  - t0198fd348e2ec8b737.jpg
  - t0177a850faae7b42f4.jpg
  - t0106a5ab61a284dcb0.jpg
  - t01e87ea37c4903393c.jpg
  - t01fbcc933afdb7affd.jpg
  - t017299242a9d351de9.jpg
  - t01fd0d30d46b598a1d.jpg
  - t019ddfb8b5b89b8475.jpg
  - t019622fab8982a72ec.jpg
  - t01bb96bd256aaad950.jpg
  - t01ba97d26345750c04.jpg
  - t01bf50d8d5d76238c6.jpg
  - t01cb6096bf8cb0a285.jpg
  - t01c4e6c901e3efda72.jpg
  - t01b58ac4d441d1b546.jpg
  - t01f3c58eaac22c8544.jpg
  - t01a58e209bfdbf852b.jpg
  - t016ff89e6fa6041712.jpg
  - t0195d14f593431562a.jpg
  - t01c6d95214927e61c0.jpg
  - t019c86a25782a7044d.jpg
  - t014a0ca534d64adbba.jpg
  - t01b24e85dc07d47b0d.jpg
  - de1934eb4ac9abdb5e8391c829f94671.jpg

# 侧边栏
sidebar:
  recent_comments: true   # 最新评论, 默认关闭, 可能需要自己进行模板配置
  hot_posts: true         # 最热文章, 如果配置了下面的文章统计就可以使用该侧边栏, 否则设置为false
  recent_posts: true      # 最新文章, 默认开启
  random_posts: true      # 随机文章, 默认开启
  tags: true              # 热门标签, 默认开启
  friend_links: true      # 友情链接, 默认开启
  links: true             # 个人链接, 默认开启

# 友情链接配置, 要先开启上面的friend_links
friend_links:
  - name: Mofan
    link: https://mofan212.gitee.io/
  - name: 派派河鉴黄师
    link: http://www.wwang.net
  - name: 加油
    link: https://shrimp_study.gitee.io/
  - name: 嚎羸
    link: https://howling.gitee.io/
  - name: Techyang
    link: https://techyang99.gitee.io/
  - name: GeekDream
    link: https://mujeyf.cn
  - name: Amadasy
    link: https://amadasy.gitee.io/
  - name: NIUBI
    link: http://47.95.208.251:8081/niubi/dist/index.html#/blog
  - name: 宇智波问天
    link: http://www.znbiscool.icu
  - name: 醉相生
    link: https://www.xsyyds.top
  - name: 那就孤雏
    link: http://60.205.188.140:8888/
  - name: jaux署记
    link: https://www.jauxgit.top
  - name: SeptZhangの小站
    link: http://septzhang.link/
  - name: 星辰驿站
    link: http://myblog.zhaixing.work/
  - name: 宇泽希
    link: https://47.93.242.4:88
  - name: 这个爱酱不太聪明
    link: https://kwydy.gitee.io/
  - name: Riven的小屋
    link: https://rivencabin.gitee.io/
  - name: 小鹏驿站
    link: https://rocpenghua.gitee.io/
  - name: 生活富能量
    link: https://budongfeng.gitee.io/weekly/
  - name: Error's Blog
    link: https://zygzyg.cloud/
# 个人链接配置, 要先开启上面的links
links:
  - name: Gitee
    link: https://gitee.com/vampireachao/
  # - name: Coding
  #   link: https://coding.net/u/SORA1
  # - name: 知乎
  #   link: https://www.zhihu.com/people/aonosora/activities


# 是否使用公告
# 公告是什么可以看https://myau.moe
# 如果使用了公告, 那么公告内容需要自己去配置
# 在主题下的layout/_partial/issue.ejs进行内容修改
# 如果不用公告, 请设置此项为false
use_issue: true

# 指定代码高亮风格
# 目前支持以下选择
# github
# railscasts
# monokai_sublime
# atom-one-dark
# darcula
highlight_theme: atom-one-dark

# 背景图功能
# 必填项
slide_background:
  # 默认为false, 即采用路径图片
  use_url: false
  # use_url: true情况下, 采用七牛外链空间的形式, 下面三个参数组合指向: http://ouo1ro65u.bkt.clouddn.com/background(1~10).png
  # prefix: http://ouo1ro65u.bkt.clouddn.com/background   七牛对象存储空间外链主机地址和图片名称前缀
  # ext: png          图片的后缀格式, 要求可供选择的图片都是统一后缀
  # max_count: 10     可供选择的图片数量, 背景图会从这里随机抽取6张图

  # use_url: false情况下, 采用本地博客图片路径, 下面三个参数组合指向: source/imgs/slide/background(1~6).jpg
  prefix: slide/background
  ext: jpg
  max_count: 6


# 是否开启欧尼酱功能
open_oni: false
# 欧尼酱功能设置, 前提为open_oni: true
oni_setting:
  # 限2项, 可以自己配置链接(一般是上面的menu或者自己的page)
  - title: 文章
    url: /archives
  - title: 关闭特效
    url: javascript:$('.cb-slideshow').hide();$('.live2d-widget-container').hide();$('.pio-container').hide();$('.live2d').hide();$('.img').hide();
  - title: Gitee
    url: https://gitee.com/vampireachao/
# 欧尼酱选项图片(可以自己替换, 最好是100 * 100像素的图片)
# 图片为默认的 source/imgs/oni/oni(1~6).jpg
# 如果自己替换了不同后缀的图片, 需要在 source/css/_common.css中修改(直接ctrl + F搜oni)


# 输入特效activate-power-mode
# https://github.com/disjukr/activate-power-mode
power_mode:
  colorful: true
  shake: true

# 文章统计, 目前只支持leancloud(可能到时添加不蒜子统计)
# 获取appId和appKey方法直接百度 or google(或者看这篇http://crescentmoon.info/2014/12/11/popular-widget/)
# 注意一旦生成新的文章就不要随便改名了
leancloud:
  appid:  # yourappId
  appkey: # your appKeym

# 评论系统, 目前只支持gitment(为了自定义样式)
# 关于gitment如何配置看这篇 https://imsun.net/posts/gitment-introduction/
# 如果不用的话要把下面的use_comment设置为false
comment:
  gitment:
      owner: # 必填项, 你的GitHub ID
      repo: # 必填项  你的存储评论的repo
      oauth:
        client_id:  # 必填项
        client_secret: # 必填项
        redirect_uri: # 可以填也可以不填

# 是否使用评论系统
use_comment: false

node_sass:
  outputStyle: compressed
  precision: 5
  sourceComments: false
# Live2D
## https://github.com/EYHN/hexo-helper-live2d
live2d:
  enable: true
  # enable: false
  scriptFrom: local # 默认
  pluginRootPath: live2dw/ # 插件在站点上的根目录(相对路径)
  pluginJsPath: lib/ # 脚本文件相对与插件根目录路径
  pluginModelPath: assets/ # 模型文件相对与插件根目录路径
  # scriptFrom: jsdelivr # jsdelivr CDN
  # scriptFrom: unpkg # unpkg CDN
  # scriptFrom: https://cdn.jsdelivr.net/npm/live2d-widget@3.x/lib/L2Dwidget.min.js # 你的自定义 url
  tagMode: false # 标签模式, 是否仅替换 live2d tag标签而非插入到所有页面中
  debug: false # 调试, 是否在控制台输出日志
  model:
    use: live2d-widget-model-z16 # npm-module package name
    # use: wanko # 博客根目录/live2d_models/ 下的目录名
    # use: ./wives/wanko # 相对于博客根目录的路径
    # use: https://cdn.jsdelivr.net/npm/live2d-widget-model-wanko@1.0.5/assets/wanko.model.json # 你的自定义 url
  display:
    position: right
    width: 150
    height: 300
  mobile:
    show: true # 手机中是否展示
